# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a4368228b496d98ebd0deb6dc0e8b3b4"
name = "my-demo-app"
handle = "my-demo-app-98"
application_url = "https://ten-diagnostic-arena-watching.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://ten-diagnostic-arena-watching.trycloudflare.com/auth/callback", "https://ten-diagnostic-arena-watching.trycloudflare.com/auth/shopify/callback", "https://ten-diagnostic-arena-watching.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
